(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const dropzone = $('dropzone'), input = $('file-input'), viewer = $('viewer'), error = $('error'), canvas = $('canvas');
  const ctx = canvas.getContext('2d'), state = { texture:null, mip:0, face:0, zoom:1, checker:true };
  const formats = { 0x31545844:'DXT1', 0x33545844:'DXT3', 0x35545844:'DXT5', 0x32495441:'ATI2', 0x31495441:'ATI1' };
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  function fail(message){ error.textContent=message; error.classList.remove('hidden'); viewer.classList.add('hidden'); dropzone.classList.remove('hidden'); }
  function openFile(file){ if(!file)return; error.classList.add('hidden'); const reader=new FileReader(); reader.onload=()=>{try{state.texture=parseDDS(reader.result,file.name); state.mip=0;state.face=0;state.zoom=1;render()}catch(e){fail(e.message||'That file could not be read as a DDS texture.')}};reader.readAsArrayBuffer(file); }
  function readDDSFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{try{resolve(parseDDS(reader.result,file.name))}catch(e){reject(e)}};reader.onerror=()=>reject(Error(`Could not read ${file.name}.`));reader.readAsArrayBuffer(file)})}
  function pngBlob(texture,face,mip){return new Promise(resolve=>{const level=texture.levels[face*texture.mips+mip],work=document.createElement('canvas');work.width=level.w;work.height=level.h;work.getContext('2d').putImageData(new ImageData(decode(level,texture.format),level.w,level.h),0,0);work.toBlob(resolve,'image/png')})}
  function pngName(texture,face,mip){const base=texture.name.replace(/\.[^.]+$/,'');return `${base}${texture.faces>1?`-face-${face+1}`:''}${texture.mips>1?`-mip-${mip}`:''}.png`}
  function downloadBlob(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  async function downloadPNG(texture,face,mip){downloadBlob(await pngBlob(texture,face,mip),pngName(texture,face,mip))}
  function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^(crc&1?0xedb88320:0)}return (crc^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32le(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}
  function joinBytes(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
  async function batchZip(files){const encoder=new TextEncoder(),local=[],central=[];let offset=0,converted=0,failed=[];for(const file of files){try{const texture=await readDDSFile(file),blob=await pngBlob(texture,0,0),bytes=new Uint8Array(await blob.arrayBuffer()),nameBytes=encoder.encode(pngName(texture,0,0)),crc=crc32(bytes),header=joinBytes([u32le(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32le(crc),u32le(bytes.length),u32le(bytes.length),u16(nameBytes.length),u16(0),nameBytes,bytes]);local.push(header);central.push(joinBytes([u32le(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32le(crc),u32le(bytes.length),u32le(bytes.length),u16(nameBytes.length),u16(0),u16(0),u16(0),u16(0),u32le(0),u32le(offset),nameBytes]));offset+=header.length;converted++}catch(e){failed.push(file.name)}}if(converted){const body=joinBytes([...local,...central]),count=central.length,centralSize=central.reduce((n,p)=>n+p.length,0),end=joinBytes([u32le(0x06054b50),u16(0),u16(0),u16(count),u16(count),u32le(centralSize),u32le(offset),u16(0)]);downloadBlob(new Blob([body,end],{type:'application/zip'}),'dds-converted-pngs.zip')}if(failed.length){error.textContent=`Converted ${converted} file${converted===1?'':'s'} to ZIP. Skipped: ${failed.join(', ')}`;error.classList.remove('hidden')}}
  async function batchConvert(files){error.classList.add('hidden');let converted=0,failed=[];for(const file of files){try{const texture=await readDDSFile(file);downloadPNG(texture,0,0);converted++;await new Promise(resolve=>setTimeout(resolve,120))}catch(e){failed.push(file.name)}}if(failed.length)fail(`${converted} converted. Could not convert: ${failed.join(', ')}`)}
  function u32(v,o){return v.getUint32(o,true)}
  function parseDDS(buffer,name){
    const v=new DataView(buffer); if(v.byteLength<128||u32(v,0)!==0x20534444)throw Error('This does not look like a DDS file.');
    const h={size:u32(v,4),flags:u32(v,8),height:u32(v,12),width:u32(v,16),pitch:u32(v,20),depth:u32(v,24),mips:u32(v,28),pfFlags:u32(v,80),fourCC:u32(v,84),rgbBits:u32(v,88),rMask:u32(v,92),gMask:u32(v,96),bMask:u32(v,100),aMask:u32(v,104),caps2:u32(v,112)};
    if(h.size!==124)throw Error('Invalid DDS header size.');
    let format=formats[h.fourCC]||null, offset=128, arraySize=1, isCube=!!(h.caps2&0x200);
    if(h.fourCC===0x30315844){ if(v.byteLength<148)throw Error('DDS DX10 header is incomplete.'); const dxgi=u32(v,128); offset=148; arraySize=u32(v,140)||1; isCube=!!(u32(v,136)&4); const names={28:'RGBA8',29:'RGBA8',87:'BGRA8',91:'BGRA8',71:'BC1',72:'BC1',74:'BC2',75:'BC2',77:'BC3',78:'BC3',80:'BC4',81:'BC4',83:'BC5',84:'BC5'}; format=names[dxgi]||`DXGI ${dxgi}`;}
    if(!format){ if(h.pfFlags&0x40){if(h.rgbBits===32)format=h.rMask===0x00ff0000?'BGRA8':'RGBA8';else if(h.rgbBits===16)format='RGB565';} else if(h.pfFlags&0x2)format='A8'; }
    if(!format||!['DXT1','DXT3','DXT5','ATI1','ATI2','RGBA8','BGRA8','RGB565','A8','BC1','BC2','BC3','BC4','BC5'].includes(format))throw Error(`Unsupported DDS format${format?`: ${format}`:''}. This viewer supports DXT1/3/5, BC4/5 and common RGBA textures.`);
    format=format.replace('BC1','DXT1').replace('BC2','DXT3').replace('BC3','DXT5').replace('BC4','ATI1').replace('BC5','ATI2');
    const faces=isCube?6:1, mips=Math.max(1,h.mips||1), levels=[]; let ptr=offset;
    for(let face=0;face<faces;face++)for(let mip=0;mip<mips;mip++){const w=Math.max(1,h.width>>mip),hh=Math.max(1,h.height>>mip),size=levelSize(w,hh,format);if(ptr+size>v.byteLength)throw Error('DDS pixel data is truncated.');levels.push({w,h:hh,data:new Uint8Array(buffer,ptr,size)});ptr+=size;}
    return {name,width:h.width,height:h.height,format,mips,faces,levels,size:buffer.byteLength,depth:h.depth||1};
  }
  function levelSize(w,h,f){return ['DXT1','ATI1'].includes(f)?Math.max(1,Math.ceil(w/4))*Math.max(1,Math.ceil(h/4))*8:['DXT3','DXT5','ATI2'].includes(f)?Math.max(1,Math.ceil(w/4))*Math.max(1,Math.ceil(h/4))*16:w*h*(f==='A8'?1:f==='RGB565'?2:4)}
  function rgb565(x){return [(x&31)*255/31,((x>>5)&63)*255/63,((x>>11)&31)*255/31]}
  function setPixel(out,w,x,y,r,g,b,a=255){if(x<0||y<0||x>=w)return;const i=(y*w+x)*4;out[i]=r;out[i+1]=g;out[i+2]=b;out[i+3]=a}
  function decodeBlock(out,w,h,x0,y0,data,kind){
    const c0=data[0]|data[1]<<8,c1=data[2]|data[3]<<8, a0=data[0], a1=data[1]; let off=4, colors=[];
    if(kind==='DXT1'||kind==='DXT3'||kind==='DXT5'){const p0=rgb565(c0),p1=rgb565(c1);colors=[p0,p1,[(2*p0[0]+p1[0])/3,(2*p0[1]+p1[1])/3,(2*p0[2]+p1[2])/3],[(p0[0]+2*p1[0])/3,(p0[1]+2*p1[1])/3,(p0[2]+2*p1[2])/3]];if(c0<=c1&&kind==='DXT1')colors[3]=[0,0,0,0];let bits=data[4]|data[5]<<8|data[6]<<16|data[7]<<24;let alphaBits=0n;if(kind==='DXT3'){alphaBits=BigInt(data[4]|data[5]<<8|data[6]<<16|data[7]<<24);bits=data[8]|data[9]<<8|data[10]<<16|data[11]<<24;}else if(kind==='DXT5'){alphaBits=BigInt(data[2])|BigInt(data[3])<<8n|BigInt(data[4])<<16n|BigInt(data[5])<<24n|BigInt(data[6])<<32n|BigInt(data[7])<<40n;bits=data[8]|data[9]<<8|data[10]<<16|data[11]<<24;}
      for(let py=0;py<4;py++)for(let px=0;px<4;px++){const ci=(bits>>((py*4+px)*2))&3,p=colors[ci];let a=255;if(kind==='DXT3')a=Number((alphaBits>>BigInt((py*4+px)*4))&15n)*17;if(kind==='DXT5'){const ai=Number((alphaBits>>BigInt((py*4+px)*3))&7n);if(a0>a1)a=ai===0?a0:ai===1?a1:((8-ai)*a0+(ai-1)*a1)/7;else a=ai===0?a0:ai===1?a1:ai===6?0:ai===7?255:((6-ai)*a0+(ai-1)*a1)/5;}setPixel(out,w,x0+px,y0+py,p[0],p[1],p[2],a)}
    } else {const alpha=kind==='ATI2'; for(let channel=0;channel<(alpha?2:1);channel++){const base=channel*8, q0=data[base],q1=data[base+1];let bits=0n;for(let i=0;i<6;i++)bits|=BigInt(data[base+2+i])<<BigInt(8*i);let table=[q0,q1];if(q0>q1)for(let i=1;i<7;i++)table.push(((7-i)*q0+i*q1)/7);else{for(let i=1;i<5;i++)table.push(((5-i)*q0+i*q1)/5);table.push(0,255)}for(let py=0;py<4;py++)for(let px=0;px<4;px++){const idx=Number((bits>>BigInt((py*4+px)*3))&7n);const val=table[idx],i=((y0+py)*w+x0+px)*4;if(alpha){out[i+channel]=val;out[i+3]=255}else out.set([val,val,val,255],i);}}}
  }
  function decode(level,format){const {w,h,data}=level,out=new Uint8ClampedArray(w*h*4);if(['DXT1','DXT3','DXT5','ATI1','ATI2'].includes(format)){for(let y=0,p=0;y<h;y+=4)for(let x=0;x<w;x+=4){const n=levelSize(Math.min(4,w-x),Math.min(4,h-y),format);decodeBlock(out,w,h,x,y,data.slice(p,p+n),format);p+=n}return out}let p=0;for(let i=0;i<w*h;i++){if(format==='A8')out[i*4+3]=data[p++];else{let r,g,b,a=255;if(format==='RGB565'){const x=data[p]|data[p+1]<<8;[r,g,b]=rgb565(x);p+=2}else{r=data[p++];g=data[p++];b=data[p++];a=data[p++];if(format==='BGRA8')[r,g,b]=[b,g,r]}out.set([r,g,b,a],i*4)}}return out}
  function render(){const t=state.texture,index=state.face*t.mips+state.mip,level=t.levels[index],pixels=decode(level,t.format);canvas.width=level.w;canvas.height=level.h;const image=new ImageData(pixels,level.w,level.h);ctx.putImageData(image,0,0);canvas.style.width=`${level.w*state.zoom}px`;canvas.style.height=`${level.h*state.zoom}px`; $('zoom-label').textContent=state.zoom===1?'100%':`${Math.round(state.zoom*100)}%`; $('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${t.width} × ${t.height}`; $('mip-count').textContent=`${state.mip+1} / ${t.mips}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');const ms=$('mip-select');ms.innerHTML='';for(let i=0;i<t.mips;i++){const l=t.levels[state.face*t.mips+i],o=new Option(`Mip ${i} · ${l.w} × ${l.h}`,i);ms.add(o)}ms.value=state.mip;$('face-control').classList.toggle('hidden',t.faces===1);$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${t.width} × ${t.height}</dd></div><div><dt>Format</dt><dd>${t.format}</dd></div><div><dt>Mip levels</dt><dd>${t.mips}</dd></div><div><dt>Faces</dt><dd>${t.faces===6?'Cube map':'1'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  function formatBytes(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`}
  $('browse').onclick=(e)=>{e.stopPropagation();input.click()};dropzone.onclick=()=>input.click();dropzone.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')input.click()};input.onchange=()=>openFile(input.files[0]);['dragenter','dragover'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add('dragover')}));['dragleave','drop'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove('dragover')}));dropzone.addEventListener('drop',e=>openFile(e.dataTransfer.files[0]));
  ['dragenter','dragover'].forEach(x=>$('viewer').addEventListener(x,e=>{e.preventDefault();$('viewer').classList.add('dragover')}));['dragleave','drop'].forEach(x=>$('viewer').addEventListener(x,e=>{e.preventDefault();$('viewer').classList.remove('dragover')}));$('viewer').addEventListener('drop',e=>{const file=[...e.dataTransfer.files].find(f=>/\.dds$/i.test(f.name)||f.type==='application/octet-stream');if(file)openFile(file)});
  const openBatchPicker=()=>{$('batch-input').click()};$('new-file').onclick=()=>input.click();$('export-png').onclick=()=>state.texture&&downloadPNG(state.texture,state.face,state.mip);$('batch-zip').onclick=e=>{e.stopPropagation();openBatchPicker()};$('batch-zip-empty').onclick=e=>{e.stopPropagation();openBatchPicker()};$('batch-input').onclick=e=>e.stopPropagation();$('batch-input').onchange=()=>{if($('batch-input').files.length){batchZip([...$('batch-input').files]);$('batch-input').value=''}};$('mip-select').onchange=e=>{state.mip=+e.target.value;render()};$('face-select').onchange=e=>{state.face=+e.target.value;render()};$('checker').onclick=()=>{state.checker=!state.checker;$('checker').classList.toggle('active',state.checker);$('stage').classList.toggle('no-checker',!state.checker)};$('zoom-in').onclick=()=>{state.zoom=clamp(state.zoom*1.25,.25,8);render()};$('zoom-out').onclick=()=>{state.zoom=clamp(state.zoom/1.25,.25,8);render()};
})();
