(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const dropzone = $('dropzone'), input = $('file-input'), viewer = $('viewer'), error = $('error'), canvas = $('canvas'), nativeImage = $('native-image');
  const ctx = canvas.getContext('2d'), state = { kind:null, texture:null, native:null, mip:0, face:0, zoom:1, checker:true };
  const formats = { 0x31545844:'DXT1', 0x33545844:'DXT3', 0x35545844:'DXT5', 0x32495441:'ATI2', 0x31495441:'ATI1' };
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  function fail(message){ error.textContent=message; error.classList.remove('hidden'); viewer.classList.add('hidden'); dropzone.classList.remove('hidden'); }
  function isDDS(file){return /\.dds$/i.test(file.name)}
  function resetPreview(){state.mip=0;state.face=0;state.zoom=1;freePanX=0;freePanY=0;canvas.style.transform='translate(0px, 0px)';nativeImage.style.transform='translate(0px, 0px)'}
  function openNative(file){const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{if(state.native?.url)URL.revokeObjectURL(state.native.url);state.kind='native';state.native={name:file.name,size:file.size,type:file.type||'Image',image,url};resetPreview();render();$('empty-stage').classList.add('hidden')};image.onerror=()=>{URL.revokeObjectURL(url);fail('This image format is not supported by your browser.')};image.src=url}
  function openFile(file){if(!file)return;error.classList.add('hidden');if(!isDDS(file)){openNative(file);return}const reader=new FileReader();reader.onload=()=>{try{if(state.native?.url)URL.revokeObjectURL(state.native.url);state.kind='dds';state.texture=parseDDS(reader.result,file.name);resetPreview();render();$('empty-stage').classList.add('hidden')}catch(e){fail(e.message||'That file could not be read as a DDS texture.')}};reader.readAsArrayBuffer(file);}
  function readDDSFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{try{resolve(parseDDS(reader.result,file.name))}catch(e){reject(e)}};reader.onerror=()=>reject(Error(`Could not read ${file.name}.`));reader.readAsArrayBuffer(file)})}
  function readNativeFile(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>resolve({name:file.name,size:file.size,type:file.type||'Image',image,url,native:true});image.onerror=()=>{URL.revokeObjectURL(url);reject(Error(`Unsupported image: ${file.name}`))};image.src=url})}
  function readViewerFile(file){return isDDS(file)?readDDSFile(file):readNativeFile(file)}
  function pngBlob(texture,face=0,mip=0){return new Promise(resolve=>{const work=document.createElement('canvas'),context=work.getContext('2d');if(texture.native){work.width=texture.image.naturalWidth;work.height=texture.image.naturalHeight;context.drawImage(texture.image,0,0)}else{const level=texture.levels[face*texture.mips+mip];work.width=level.w;work.height=level.h;context.putImageData(new ImageData(decode(level,texture.format),level.w,level.h),0,0)}work.toBlob(resolve,'image/png')})}
  function pngName(texture,face,mip){const base=texture.name.replace(/\.[^.]+$/,'');return `${base}${texture.faces>1?`-face-${face+1}`:''}${texture.mips>1?`-mip-${mip}`:''}.png`}
  function downloadBlob(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  async function downloadPNG(texture,face,mip){downloadBlob(await pngBlob(texture,face,mip),pngName(texture,face,mip))}
  function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^(crc&1?0xedb88320:0)}return (crc^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32le(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}
  function joinBytes(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
  async function batchZip(files){error.classList.add('hidden');const encoder=new TextEncoder(),local=[],central=[],usedNames=new Set();let offset=0,converted=0,failed=[];for(const file of files){try{const texture=await readViewerFile(file),blob=await pngBlob(texture,0,0),bytes=new Uint8Array(await blob.arrayBuffer());if(texture.url)URL.revokeObjectURL(texture.url);let name=pngName(texture,0,0),suffix=2;while(usedNames.has(name)){name=pngName(texture,0,0).replace(/\.png$/,`-${suffix++}.png`)}usedNames.add(name);const nameBytes=encoder.encode(name),crc=crc32(bytes),header=joinBytes([u32le(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32le(crc),u32le(bytes.length),u32le(bytes.length),u16(nameBytes.length),u16(0),nameBytes,bytes]);local.push(header);central.push(joinBytes([u32le(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32le(crc),u32le(bytes.length),u32le(bytes.length),u16(nameBytes.length),u16(0),u16(0),u16(0),u16(0),u32le(0),u32le(offset),nameBytes]));offset+=header.length;converted++}catch(e){failed.push(file.name)}}if(converted){const body=joinBytes([...local,...central]),count=central.length,centralSize=central.reduce((n,p)=>n+p.length,0),end=joinBytes([u32le(0x06054b50),u16(0),u16(0),u16(count),u16(count),u32le(centralSize),u32le(offset),u16(0)]);downloadBlob(new Blob([body,end],{type:'application/zip'}),'image-conversions.zip')}if(failed.length){error.textContent=converted?`Converted ${converted} file${converted===1?'':'s'} to ZIP. Skipped: ${failed.join(', ')}`:`No files could be converted. Skipped: ${failed.join(', ')}`;error.classList.remove('hidden')}}
  function u32(v,o){return v.getUint32(o,true)}
  function parseDDS(buffer,name){
    const v=new DataView(buffer); if(v.byteLength<128||u32(v,0)!==0x20534444)throw Error('This does not look like a DDS file.');
    const h={size:u32(v,4),flags:u32(v,8),height:u32(v,12),width:u32(v,16),pitch:u32(v,20),depth:u32(v,24),mips:u32(v,28),pfFlags:u32(v,80),fourCC:u32(v,84),rgbBits:u32(v,88),rMask:u32(v,92),gMask:u32(v,96),bMask:u32(v,100),aMask:u32(v,104),caps2:u32(v,112)};
    if(h.size!==124)throw Error('Invalid DDS header size.');
    let format=formats[h.fourCC]||null, offset=128, arraySize=1, isCube=!!(h.caps2&0x200);
    if(h.fourCC===0x30315844){ if(v.byteLength<148)throw Error('DDS DX10 header is incomplete.'); const dxgi=u32(v,128); offset=148; arraySize=u32(v,140)||1; isCube=!!(u32(v,136)&4); const names={11:'RGBA16',24:'RGB10A2',28:'RGBA8',29:'RGBA8',49:'RG8',61:'R8',65:'A8',71:'BC1',72:'BC1',74:'BC2',75:'BC2',77:'BC3',78:'BC3',80:'BC4',81:'BC4',83:'BC5',84:'BC5',85:'RGB565',86:'ARGB1555',87:'BGRA8',91:'BGRA8',115:'ARGB4444'}; format=names[dxgi]||`DXGI ${dxgi}`;}
    if(!format){if(h.pfFlags&0x40){if(h.rgbBits===32){if(h.rMask===0x3ff&&h.gMask===0xffc00&&h.bMask===0x3ff00000)format='RGB10A2';else if(h.rMask===0x00ff0000&&h.gMask===0x0000ff00&&h.bMask===0x000000ff)format='BGRA8';else if(h.rMask===0x000000ff&&h.gMask===0x0000ff00&&h.bMask===0x00ff0000)format='RGBA8'}else if(h.rgbBits===24&&h.rMask===0x00ff0000&&h.gMask===0x0000ff00&&h.bMask===0x000000ff)format='BGR8';else if(h.rgbBits===16){if(h.rMask===0xf800&&h.gMask===0x07e0&&h.bMask===0x001f)format='RGB565';else if(h.rMask===0x7c00&&h.gMask===0x03e0&&h.bMask===0x001f)format='ARGB1555';else if(h.rMask===0x0f00&&h.gMask===0x00f0&&h.bMask===0x000f)format='ARGB4444'}}else if(h.pfFlags&0x20000)format=h.rgbBits===16?'L8A8':'L8';else if(h.pfFlags&0x2)format='A8';}
    if(!format||!['DXT1','DXT3','DXT5','ATI1','ATI2','RGBA8','BGRA8','RGB565','ARGB1555','ARGB4444','RGB10A2','RGBA16','BGR8','R8','RG8','L8','L8A8','A8','BC1','BC2','BC3','BC4','BC5'].includes(format))throw Error(`Unsupported DDS format${format?`: ${format}`:''}. This viewer supports BC1–BC5, common RGBA, luminance, and packed 16/32-bit textures.`);
    format=format.replace('BC1','DXT1').replace('BC2','DXT3').replace('BC3','DXT5').replace('BC4','ATI1').replace('BC5','ATI2');
    if(arraySize>1||h.depth>1)throw Error('DDS texture arrays and volume textures are not supported yet.');
    const faces=isCube?6:1, mips=Math.max(1,h.mips||1), levels=[]; let ptr=offset;
    for(let face=0;face<faces;face++)for(let mip=0;mip<mips;mip++){const w=Math.max(1,h.width>>mip),hh=Math.max(1,h.height>>mip),size=levelSize(w,hh,format);if(ptr+size>v.byteLength)throw Error('DDS pixel data is truncated.');levels.push({w,h:hh,data:new Uint8Array(buffer,ptr,size)});ptr+=size;}
    return {name,width:h.width,height:h.height,format,mips,faces,levels,size:buffer.byteLength,depth:h.depth||1};
  }
  function levelSize(w,h,f){return ['DXT1','ATI1'].includes(f)?Math.max(1,Math.ceil(w/4))*Math.max(1,Math.ceil(h/4))*8:['DXT3','DXT5','ATI2'].includes(f)?Math.max(1,Math.ceil(w/4))*Math.max(1,Math.ceil(h/4))*16:w*h*(['A8','R8','L8'].includes(f)?1:['RGB565','ARGB1555','ARGB4444','L8A8','RG8'].includes(f)?2:f==='BGR8'?3:f==='RGBA16'?8:4)}
  function rgb565(x){return [(x&31)*255/31,((x>>5)&63)*255/63,((x>>11)&31)*255/31]}
  function setPixel(out,w,h,x,y,r,g,b,a=255){if(x<0||y<0||x>=w||y>=h)return;const i=(y*w+x)*4;out[i]=r;out[i+1]=g;out[i+2]=b;out[i+3]=a}
  function decodeBlock(out,w,h,x0,y0,data,kind){
    const c0=data[0]|data[1]<<8,c1=data[2]|data[3]<<8, a0=data[0], a1=data[1]; let off=4, colors=[];
    if(kind==='DXT1'||kind==='DXT3'||kind==='DXT5'){const p0=rgb565(c0),p1=rgb565(c1);colors=[p0,p1,[(2*p0[0]+p1[0])/3,(2*p0[1]+p1[1])/3,(2*p0[2]+p1[2])/3],[(p0[0]+2*p1[0])/3,(p0[1]+2*p1[1])/3,(p0[2]+2*p1[2])/3]];if(c0<=c1&&kind==='DXT1')colors[3]=[0,0,0,0];let bits=data[4]|data[5]<<8|data[6]<<16|data[7]<<24;let alphaBits=0n;if(kind==='DXT3'){alphaBits=BigInt(data[4]|data[5]<<8|data[6]<<16|data[7]<<24);bits=data[8]|data[9]<<8|data[10]<<16|data[11]<<24;}else if(kind==='DXT5'){alphaBits=BigInt(data[2])|BigInt(data[3])<<8n|BigInt(data[4])<<16n|BigInt(data[5])<<24n|BigInt(data[6])<<32n|BigInt(data[7])<<40n;bits=data[8]|data[9]<<8|data[10]<<16|data[11]<<24;}
      for(let py=0;py<4;py++)for(let px=0;px<4;px++){const ci=(bits>>((py*4+px)*2))&3,p=colors[ci];let a=255;if(kind==='DXT3')a=Number((alphaBits>>BigInt((py*4+px)*4))&15n)*17;if(kind==='DXT5'){const ai=Number((alphaBits>>BigInt((py*4+px)*3))&7n);if(a0>a1)a=ai===0?a0:ai===1?a1:((8-ai)*a0+(ai-1)*a1)/7;else a=ai===0?a0:ai===1?a1:ai===6?0:ai===7?255:((6-ai)*a0+(ai-1)*a1)/5;}setPixel(out,w,h,x0+px,y0+py,p[0],p[1],p[2],a)}
    } else {const twoChannel=kind==='ATI2'; for(let channel=0;channel<(twoChannel?2:1);channel++){const base=channel*8, q0=data[base],q1=data[base+1];let bits=0n;for(let i=0;i<6;i++)bits|=BigInt(data[base+2+i])<<BigInt(8*i);let table=[q0,q1];if(q0>q1)for(let i=1;i<7;i++)table.push(((7-i)*q0+i*q1)/7);else{for(let i=1;i<5;i++)table.push(((5-i)*q0+i*q1)/5);table.push(0,255)}for(let py=0;py<4;py++)for(let px=0;px<4;px++){const x=x0+px,y=y0+py;if(x>=w||y>=h)continue;const idx=Number((bits>>BigInt((py*4+px)*3))&7n),val=table[idx],i=(y*w+x)*4;if(twoChannel){out[i+channel]=val;out[i+3]=255}else out.set([val,val,val,255],i);}}}
  }
  function decode(level,format){const {w,h,data}=level,out=new Uint8ClampedArray(w*h*4);if(['DXT1','DXT3','DXT5','ATI1','ATI2'].includes(format)){for(let y=0,p=0;y<h;y+=4)for(let x=0;x<w;x+=4){const n=levelSize(Math.min(4,w-x),Math.min(4,h-y),format);decodeBlock(out,w,h,x,y,data.slice(p,p+n),format);p+=n}return out}let p=0;for(let i=0;i<w*h;i++){let r=0,g=0,b=0,a=255,x;if(['A8'].includes(format)){a=data[p++]}else if(['R8','L8'].includes(format)){r=g=b=data[p++]}else if(format==='L8A8'){r=g=b=data[p++];a=data[p++]}else if(format==='RG8'){r=data[p++];g=data[p++]}else if(format==='BGR8'){b=data[p++];g=data[p++];r=data[p++]}else if(format==='RGB565'){x=data[p]|data[p+1]<<8;[r,g,b]=rgb565(x);p+=2}else if(format==='ARGB1555'){x=data[p]|data[p+1]<<8;r=((x>>10)&31)*255/31;g=((x>>5)&31)*255/31;b=(x&31)*255/31;a=x&0x8000?255:0;p+=2}else if(format==='ARGB4444'){x=data[p]|data[p+1]<<8;r=((x>>8)&15)*17;g=((x>>4)&15)*17;b=(x&15)*17;a=((x>>12)&15)*17;p+=2}else if(format==='RGB10A2'){x=(data[p]|data[p+1]<<8|data[p+2]<<16|data[p+3]<<24)>>>0;r=(x&1023)*255/1023;g=((x>>10)&1023)*255/1023;b=((x>>>20)&1023)*255/1023;a=((x>>>30)&3)*85;p+=4}else if(format==='RGBA16'){r=(data[p]|data[p+1]<<8)/257;g=(data[p+2]|data[p+3]<<8)/257;b=(data[p+4]|data[p+5]<<8)/257;a=(data[p+6]|data[p+7]<<8)/257;p+=8}else{r=data[p++];g=data[p++];b=data[p++];a=data[p++];if(format==='BGRA8')[r,g,b]=[b,g,r]}out.set([r,g,b,a],i*4)}return out}
  function render(){const t=state.texture,index=state.face*t.mips+state.mip,level=t.levels[index],pixels=decode(level,t.format);canvas.width=level.w;canvas.height=level.h;const image=new ImageData(pixels,level.w,level.h);ctx.putImageData(image,0,0);canvas.style.width=`${level.w*state.zoom}px`;canvas.style.height=`${level.h*state.zoom}px`; $('zoom-label').textContent=state.zoom===1?'100%':`${Math.round(state.zoom*100)}%`; $('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${t.width} × ${t.height}`; $('mip-count').textContent=`${state.mip+1} / ${t.mips}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');const ms=$('mip-select');ms.innerHTML='';for(let i=0;i<t.mips;i++){const l=t.levels[state.face*t.mips+i],o=new Option(`Mip ${i} · ${l.w} × ${l.h}`,i);ms.add(o)}ms.value=state.mip;$('face-control').classList.toggle('hidden',t.faces===1);$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${t.width} × ${t.height}</dd></div><div><dt>Format</dt><dd>${t.format}</dd></div><div><dt>Mip levels</dt><dd>${t.mips}</dd></div><div><dt>Faces</dt><dd>${t.faces===6?'Cube map':'1'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  function formatBytes(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`}
  $('browse').onclick=(e)=>{e.stopPropagation();input.click()};dropzone.onclick=()=>input.click();dropzone.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')input.click()};input.onchange=()=>openFile(input.files[0]);['dragenter','dragover'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add('dragover')}));['dragleave','drop'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove('dragover')}));dropzone.addEventListener('drop',e=>openFile(e.dataTransfer.files[0]));
  ['dragenter','dragover'].forEach(x=>$('viewer').addEventListener(x,e=>{e.preventDefault();$('viewer').classList.add('dragover')}));['dragleave','drop'].forEach(x=>$('viewer').addEventListener(x,e=>{e.preventDefault();$('viewer').classList.remove('dragover')}));$('viewer').addEventListener('drop',e=>{const file=[...e.dataTransfer.files].find(f=>/\.dds$/i.test(f.name)||f.type==='application/octet-stream');if(file)openFile(file)});
  const openBatchPicker=()=>{$('batch-input').click()};$('new-file').onclick=()=>input.click();$('export-png').onclick=()=>state.texture&&downloadPNG(state.texture,state.face,state.mip);$('batch-zip').onclick=e=>{e.stopPropagation();openBatchPicker()};$('batch-zip-empty').onclick=e=>{e.stopPropagation();openBatchPicker()};$('batch-input').onclick=e=>e.stopPropagation();$('batch-input').onchange=()=>{if($('batch-input').files.length){batchZip([...$('batch-input').files]);$('batch-input').value=''}};$('mip-select').onchange=e=>{state.mip=+e.target.value;render()};$('face-select').onchange=e=>{state.face=+e.target.value;render()};$('checker').onclick=()=>{state.checker=!state.checker;$('checker').classList.toggle('active',state.checker);$('stage').classList.toggle('no-checker',!state.checker)};$('zoom-in').onclick=()=>{state.zoom=clamp(state.zoom*1.25,.25,8);render()};$('zoom-out').onclick=()=>{state.zoom=clamp(state.zoom/1.25,.25,8);render()};
  const stage=$('stage');let freeDragging=false,freeX=0,freeY=0,freePanX=0,freePanY=0;stage.addEventListener('pointerdown',e=>{if(e.button!==0||!state.texture)return;freeDragging=true;freeX=e.clientX;freeY=e.clientY;stage.classList.add('panning');stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!freeDragging)return;freePanX+=e.clientX-freeX;freePanY+=e.clientY-freeY;freeX=e.clientX;freeY=e.clientY;canvas.style.transform=`translate(${freePanX}px, ${freePanY}px)`});stage.addEventListener('pointerup',e=>{freeDragging=false;stage.classList.remove('panning');if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId)});stage.addEventListener('pointercancel',()=>{freeDragging=false;stage.classList.remove('panning')});stage.addEventListener('wheel',e=>{if(!state.texture)return;e.preventDefault();state.zoom=clamp(state.zoom*(e.deltaY<0?1.15:1/1.15),.25,8);render()},{passive:false});$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('viewer').requestFullscreen?.()};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'⛶ Exit fullscreen':'⛶ Fullscreen'});
  function renderDDS(){const t=state.texture,index=state.face*t.mips+state.mip,level=t.levels[index],pixels=decode(level,t.format);canvas.width=level.w;canvas.height=level.h;ctx.putImageData(new ImageData(pixels,level.w,level.h),0,0);canvas.style.width=`${level.w*state.zoom}px`;canvas.style.height=`${level.h*state.zoom}px`;canvas.classList.remove('hidden');nativeImage.classList.add('hidden');$('file-badge').textContent='DDS';$('zoom-label').textContent=`${Math.round(state.zoom*100)}%`;$('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${t.width} × ${t.height}`;$('mip-count').textContent=`${state.mip+1} / ${t.mips}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');$('mip-control').classList.remove('hidden');const ms=$('mip-select');ms.innerHTML='';for(let i=0;i<t.mips;i++){const l=t.levels[state.face*t.mips+i];ms.add(new Option(`Mip ${i} · ${l.w} × ${l.h}`,i))}ms.value=state.mip;$('face-control').classList.toggle('hidden',t.faces===1);$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${t.width} × ${t.height}</dd></div><div><dt>Format</dt><dd>${t.format}</dd></div><div><dt>Mip levels</dt><dd>${t.mips}</dd></div><div><dt>Faces</dt><dd>${t.faces===6?'Cube map':'1'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  function renderNative(){const t=state.native;width=t.image.naturalWidth;height=t.image.naturalHeight;nativeImage.src=t.url;nativeImage.style.width=`${width*state.zoom}px`;nativeImage.style.height=`${height*state.zoom}px`;nativeImage.classList.remove('hidden');canvas.classList.add('hidden');$('file-badge').textContent='IMAGE';$('zoom-label').textContent=`${Math.round(state.zoom*100)}%`;$('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${width} × ${height}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');$('mip-control').classList.add('hidden');$('face-control').classList.add('hidden');$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${width} × ${height}</dd></div><div><dt>Format</dt><dd>${t.type}</dd></div><div><dt>Animation</dt><dd>${/gif|webp|avif|png/i.test(t.type)?'Browser playback':'Still image'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  function render(){if(state.kind==='native')renderNative();else renderDDS()}
  function renderNative(){const t=state.native,width=t.image.naturalWidth,height=t.image.naturalHeight;nativeImage.src=t.url;nativeImage.style.width=`${width*state.zoom}px`;nativeImage.style.height=`${height*state.zoom}px`;nativeImage.classList.remove('hidden');canvas.classList.add('hidden');$('file-badge').textContent='IMAGE';$('zoom-label').textContent=`${Math.round(state.zoom*100)}%`;$('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${width} × ${height}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');$('mip-control').classList.add('hidden');$('face-control').classList.add('hidden');$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${width} × ${height}</dd></div><div><dt>Format</dt><dd>${t.type}</dd></div><div><dt>Animation</dt><dd>${/gif|webp|avif|png/i.test(t.type)?'Browser playback':'Still image'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  function renderNative(){const t=state.native,width=t.image.naturalWidth,height=t.image.naturalHeight;if(nativeImage.src!==t.url)nativeImage.src=t.url;nativeImage.style.width=`${width*state.zoom}px`;nativeImage.style.height=`${height*state.zoom}px`;nativeImage.classList.remove('hidden');canvas.classList.add('hidden');$('file-badge').textContent='IMAGE';$('zoom-label').textContent=`${Math.round(state.zoom*100)}%`;$('file-name').textContent=t.name;$('file-meta').textContent=`${formatBytes(t.size)} · ${width} × ${height}`;viewer.classList.remove('hidden');dropzone.classList.add('hidden');$('mip-control').classList.add('hidden');$('face-control').classList.add('hidden');$('details-list').innerHTML=`<div><dt>Dimensions</dt><dd>${width} × ${height}</dd></div><div><dt>Format</dt><dd>${t.type}</dd></div><div><dt>Animation</dt><dd>${/gif|webp|avif|png/i.test(t.type)?'Browser playback':'Still image'}</dd></div><div><dt>File size</dt><dd>${formatBytes(t.size)}</dd></div>`}
  $('export-png').onclick=()=>{const asset=state.kind==='native'?state.native:state.texture;if(asset)downloadPNG(asset,state.face,state.mip)};
  viewer.addEventListener('drop',e=>{e.preventDefault();e.stopImmediatePropagation();viewer.classList.remove('dragover');const file=e.dataTransfer.files[0];if(file)openFile(file)},true);
  let nativeDragging=false,nativeX=0,nativeY=0;stage.addEventListener('pointerdown',e=>{if(state.kind!=='native'||e.button!==0)return;nativeDragging=true;nativeX=e.clientX;nativeY=e.clientY;stage.setPointerCapture(e.pointerId);e.stopImmediatePropagation()},true);stage.addEventListener('pointermove',e=>{if(!nativeDragging)return;freePanX+=e.clientX-nativeX;freePanY+=e.clientY-nativeY;nativeX=e.clientX;nativeY=e.clientY;nativeImage.style.transform=`translate(${freePanX}px, ${freePanY}px)`;e.stopImmediatePropagation()},true);stage.addEventListener('pointerup',e=>{if(!nativeDragging)return;nativeDragging=false;if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);e.stopImmediatePropagation()},true);
  stage.addEventListener('wheel',e=>{if(state.kind!=='native')return;e.preventDefault();e.stopImmediatePropagation();state.zoom=clamp(state.zoom*(e.deltaY<0?1.15:1/1.15),.25,8);render()},{passive:false,capture:true});
})();
